### ISSUE TITLE
Connecting to PlanetScale Database

### ISSUE THREAD

**Issue by joshourisman** [gregmsanderson/fly-hello-wordpress#2]
This seems like it should be simple, but Wordpress/PHP is not really my forte, and I’m having a hell of a time finding any good documentation for this. Since the README mentions that this was tested against PlanetScale, how did you actually get Wordpress to connect? I’m setting my environment variables as follows, but I keep getting database connection errors (it works just fine against a Google Cloud SQL MySQL database, but I’m trying to migrate it to PlanetScale). Based on what I can tell from the connection details provided for Django and others, it seems like I need to specify the CA root, but I cannot find a single example of how to do that for Wordpress.

```
-e WORDPRESS_DB_HOST='…' \
-e WORDPRESS_DB_USER='…' \
-e WORDPRESS_DB_PASSWORD='…' \
-e WORDPRESS_DB_NAME='…' \
-e WORDPRESS_CONFIG_EXTRA='define("MYSQL_CLIENT_FLAGS", MYSQLI_CLIENT_SSL);' 
```

**Comment by gregmsanderson** [comment]
Yep, I did connect to a PlanetScale database when writing that README. So it _should_ work. At least it _did_ when I wrote it. Strange.

I recall I could not connect until I added that additional flag, for MYSQL_CLIENT_FLAGS. That came from _this_ answer to the same question:

https://github.com/planetscale/discussion/discussions/214#discussioncomment-2911698

And for another guy too, finding the same:

https://community.fly.io/t/how-to-deploy-wordpress-on-fly/6274

The CA root should be an OS-thing since PlanetScale is using a trusted certificate.  I don't think it should be applicable here, because this repo is based on the official WordPress image (that's basically all there is in the Dockerfile) and so _that_ would specify the base OS etc. Didn't delve into that, but I think we can assume they would use an image set up with trusted CA etc already.

Any luck with adding the _WORDPRESS_DEBUG_ flag? Did that reveal any more about why it couldn't connect?

Are you running the image locally, or deployed on some PaaS like Fly?

**Comment by joshourisman** [comment]
Strange. Setting WORDPRESS_DEBUG gives me absolutely nothing. When I try to visit the site in the container I get a database connection error, but no errors are logged to the console.

At the moment I’m working on installing the pscale CLI into my container, so I can use the proxy function to hopefully connect that way.

For now I’m running it locally (well, on Gitpod), but the live Wordpress site is already deployed on Fly.io pointing to the existing Google Cloud SQL database, so the plan is to deploy this there, once I get the database connection figured out.

**Comment by joshourisman** [comment]
Haven’t tracked down exactly why this is happening yet, but I put the MYSQL_CLIENT_FLAGS directly in the wp-config.php file, and copied it into the container, and now it works!

Thanks for your help!

**Comment by gregmsanderson** [comment]
@joshourisman  No problem, glad it's working.

That _shouldn't_ be needed as the container should respect the environment variable setting that same flag. But hey, if it works, all good.

I had a look into the CA stuff and see why that gets mentioned: https://planetscale.com/docs/concepts/secure-connections#why-do-i-need-to-care-about-a-ca-when-connecting-to-planetscale But when _I_ ran it from Fly, I didn't need to do anything beyond what's in the README.

**Comment by joshourisman** [comment]
Turns out I wasn't paying enough attention, and this Wordpress container, was packaging its own wp-config.php with some modifications, and didn't look for all the necessary environment variables. Updating it to check for everything solved that.

I'm now running into an issue with the PlanetScale database import for some reason putting Wordpress into install mode, but that seems unrelated…

**Comment by joshourisman** [comment]
FYI, I've been [talking to the PlanetScale team](https://github.com/planetscale/discussion/discussions/352), and it turns out that PlanetScale won't actually work for a production Wordpress site. Basically, Wordpress requires schema-altering capabilities to run, so they it can handle updates and plugin installations, and if it doesn't have that it doesn't work (and annoyingly just gives you the install screen). PlanetScale doesn't allow that for the main branch of production databases, so the instance you flip your database to production, your Wordpress site stops working.

It sounds like it would require some pretty significant changes to Wordpress to address this, though I don't really know enough about the inner workings of Wordpress to comments on that, but hopefully it's something that will be possible in the future, because PlanetScale could really solve some of the annoyances of working with Wordpress!

**Comment by gregmsanderson** [comment]
@joshourisman _Ah_ ... interesting. You make a _very_ good point.

I too had discussed WordPress with them (for a different reason) and that was never mentioned! Guess they didn't realise either. I guess I hadn't tried installing any plugin and so I guess the issue wouldn't arise. Since it's only when you need to _change_ schema after the initial installation that you'd find the (by then) production branch says no. As you did.

I think it's unlikely WordPress will change but in theory PlanetScale could add an allow-schema-changes-in-production option. That's probably _more_ likely. But maybe still unlikely. And it doesn't solve the problem right now. Sigh.

**Comment by joshourisman** [comment]
Well, it may actually be a problem with the specific Wordpress site I was trying to migrate, and not actually any sort of incompatibility between Wordpress and PlanetScale. I was able to create a fresh install running on Fly.io and using a PlanetScale database, and it appears to be working fine. I will be more than a little annoyed if it's just this specific Wordpress site that can't use PlanetScale, as it's one that I inherited support for, and it's already a huge mess, which is why I wanted to get it on PlanetScale so I could safely and easily test changes to it…
